% aja_emg_sarjassa('E:\MEP sorting\MEP10\','jv_nomas_EXP_1.TXT','jv_nomas_EXP_2.TXT','nomasking_APB')
% aja_emg_sarjassa('E:\MEP sorting\MEP10\','jv_nomas_EXP_1.TXT','jv_nomas_EXP_3.TXT','nomasking_ADM')
% aja_emg_sarjassa('E:\MEP sorting\MEP10\','jv_1_EXP_1.TXT','jv_1_EXP_2.TXT','1_APB')
% aja_emg_sarjassa('E:\MEP sorting\MEP10\','jv_1_EXP_1.TXT','jv_1_EXP_3.TXT','1_ADM')
% aja_emg_sarjassa('E:\MEP sorting\MEP10\','jv_2_EXP_1.TXT','jv_2_EXP_2.TXT','2_APB')
% aja_emg_sarjassa('E:\MEP sorting\MEP10\','jv_2_EXP_1.TXT','jv_2_EXP_3.TXT','2_ADM')
% aja_emg_sarjassa('E:\MEP sorting\MEP11\','te_nomas_EXP_1.TXT','te_nomas_EXP_2.TXT','nomasking_APB')
% aja_emg_sarjassa('E:\MEP sorting\MEP11\','te_nomas_EXP_1.TXT','te_nomas_EXP_3.TXT','nomasking_ADM')
% aja_emg_sarjassa('E:\MEP sorting\MEP11\','te_1_EXP_1.TXT','te_1_EXP_2.TXT','1_APB')
% aja_emg_sarjassa('E:\MEP sorting\MEP11\','te_1_EXP_1.TXT','te_1_EXP_3.TXT','1_ADM')
% aja_emg_sarjassa('E:\MEP sorting\MEP11\','te_2_EXP_1.TXT','te_2_EXP_2.TXT','2_APB')
% aja_emg_sarjassa('E:\MEP sorting\MEP11\','te_2_EXP_1.TXT','te_2_EXP_3.TXT','2_ADM')

aja_emg_sarjassa('E:\MEP sorting\MEP10\','jv_3_EXP_1.TXT','jv_3_EXP_2.TXT','3_APB')
aja_emg_sarjassa('E:\MEP sorting\MEP10\','jv_3_EXP_1.TXT','jv_3_EXP_3.TXT','3_ADM')
aja_emg_sarjassa('E:\MEP sorting\MEP11\','te_3_EXP_1.TXT','te_3_EXP_2.TXT','3_APB')
aja_emg_sarjassa('E:\MEP sorting\MEP11\','te_3_EXP_1.TXT','te_3_EXP_3.TXT','3_ADM')